### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by Mrxuefei** [leopiney/deep-forest#5]
Thanks for your implementation！
When I want to train my model，I have a x_train(32300,92160) y_train(32300,1),but I got an error:

<MultiGrainedScanner stride_ratio=0.25> - Scanning and fitting for X ((32300,)) and y ((32300,)) started
<MultiGrainedScanner stride_ratio=0.25> - Window shape: [1, 23040] Total windows: 69121
Traceback (most recent call last):
  File "gcForest_fer.py", line 71, in <module>
    mgc_forest.fit(x_train, y_train)
  File "/home/wangjian/wj/deep_forest.py", line 68, in fit
    for mgs in self.mgs_instances
  File "/home/wangjian/wj/deep_forest.py", line 191, in scan
    sliced_X, sliced_y = self.slices(X, y)
  File "/home/wangjian/wj/deep_forest.py", line 154, in slices
    windows_slices_list = X[(slice(None),) + axis_slices]
IndexError: too many indices for array.
Can you tell me why I am wrong? Thank you!

**Comment by leopiney** [comment]
Hi @Mrxuefei

I've just merged a PR with some major improvements on the MGS algorithm. Can you try again with the latest version of the code?

Kind regards,
